name: Run CVX Predictor Daily

on:
  schedule:
    - cron: '30 13 * * *'  # 13:30 UTC = 14:30 italiane (in inverno)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install yfinance scikit-learn pandas numpy requests

      - name: Run predictor
        run: python cvx_predictor.py
